# Generated by Django 5.2.8 on 2025-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='controller',
            new_name='event_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='shop_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='shopper',
            field=models.BooleanField(default=False),
        ),
    ]
