# Generated by Django 5.2.8 on 2025-12-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_controller_user_event_admin_user_shop_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_auth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('apple', 'Apple'), ('facebook', 'Facebook'), ('email', 'Email/Password'), ('other', 'Other')], default='email', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
