# Generated by Django 5.2.8 on 2025-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_conditions', 'Terms & Conditions'), ('about_us', 'About Us')], max_length=20, unique=True)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='common_data/images/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='common_data/images/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='common_data/images/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='common_data/images/')),
            ],
        ),
    ]
