# Generated by Django 5.2.8 on 2025-12-23 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopadmin', '0009_shoppercheckin_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEntryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(default='Event Creation Fee', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('revenuecat_product_id_android', models.CharField(blank=True, max_length=100, null=True)),
                ('revenuecat_product_id_ios', models.CharField(blank=True, max_length=100, null=True)),
                ('revenuecat_product_id_web', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Entry Fee',
                'verbose_name_plural': 'Event Entry Fees',
            },
        ),
        migrations.CreateModel(
            name='EarningsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('android_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ios_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('web_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Earnings Summary',
                'verbose_name_plural': 'Earnings Summaries',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EventAdminPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenuecat_transaction_id', models.CharField(max_length=255, unique=True)),
                ('revenuecat_user_id', models.CharField(max_length=255)),
                ('revenuecat_product_id', models.CharField(max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('store_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_month', models.IntegerField(blank=True, null=True)),
                ('payment_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_payment', to='shopadmin.event')),
                ('event_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_payments', to=settings.AUTH_USER_MODEL)),
                ('entry_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.evententryfee')),
            ],
            options={
                'verbose_name': 'Event Admin Payment',
                'verbose_name_plural': 'Event Admin Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
