# Generated by Django 5.2.8 on 2025-12-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0003_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventshopparticipant',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='eventshopparticipant',
            name='rejected',
        ),
    ]
