# Generated by Django 5.2.8 on 2025-12-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0005_eventshopparticipant_shopper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventshop',
            options={},
        ),
        migrations.AddField(
            model_name='eventshop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
