# Generated by Django 5.2.8 on 2025-12-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0006_alter_eventshop_options_eventshop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventshopparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
