# Generated by Django 5.2.8 on 2025-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0007_eventshopparticipant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpassport',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpassport',
            name='total_visits',
            field=models.IntegerField(default=0),
        ),
    ]
