# Generated by Django 5.2.8 on 2025-12-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0008_eventpassport_is_visited_eventpassport_total_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppercheckin',
            name='status',
            field=models.CharField(choices=[('stamped', 'Stamped'), ('visited', 'Visited')], default='stamped', max_length=20),
        ),
    ]
