# Generated by Django 5.2.8 on 2025-12-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shop_cover_image_shopcoverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
