upstream backend {
    server api:8000;
}

server {
    listen 80;
    server_name shophopapp.com www.shophopapp.com api.shophopapp.com;

    client_max_body_size 500M;

    # Certbot challenge - MUST BE FIRST!
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    # Static files
    location /static/ {
        alias /app/staticfiles/;
    }

    # Media files
    location /media/ {
        alias /app/media/;
    }

    # Main backend API and routes - LAST!
    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}